export const MAIN = '#1ABC9C'
export const TEXT = '#4B4B4B'
export const LIGHT_TEXT = '#BEBEBE'
export const DARKER_GRAY = '#bcbcbc'
export const BACKGROUND_GRAY = '#EBEFF1' // '#F5F5F7'
export const TINT = '#34495E'
export const IOS_FONT = 'Futura'
export const IOS_FONT_BOLD = 'ChalkboardSE-Bold'
